modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = "https://discord.gg/Vqu6wYZwdZ"
license = "ARR"

[[mods]]
modId = "bakery"
version = "${version}"
displayName = "Bakery"
authors = "Satisfy"
description = '''
A Mod all about crafting Bread, Cakes and Pastry'''
logoFile = "pack.png"

[[dependencies.bakery]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "doapi"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"