modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = "https://discord.gg/Vqu6wYZwdZ"
license = "ARR"

[[mods]]
modId = "bakery"
version = "${version}"
displayName = "Bakery"
authors = "Satisfy"
description = '''
A Mod all about crafting Bread, Cakes and Pastry'''
logoFile = "pack.png"

[[dependencies.bakery]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"