modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"

[[mixins]]
config = "bakery-common.mixins.json"

[[mods]]
modId = "bakery"
version = "2.1.0"
displayName = "[Let's Do] Bakery"
authors = "Satisfy, Binaris"
description = '''
Build your own bakery, bake the finest pastries, delicious bread, and sweet cakes!'''
logoFile = "pack.png"

[[dependencies.bakery]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "doapi"
type = "required"
versionRange = "[1.2.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bakery]]
modId = "farm_and_charm"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"